services:
  ruifrite:
    build: .
    container_name: modrinth-server
    ports:
      - "25565:25565"
    volumes:
      - .data/modrinth-server:/app/mcserver
    environment:
      MRPACK_URL: # direct url to a .mrpack modpack file
      JAVA_ARGS: "-Xmx6G -Xms4G"

    restart: unless-stopped

